### ISSUE TITLE
Infografia ciclo de desarrollo de software

### ISSUE THREAD

**Issue by Yareli-Perez** [SistemasTecTlaxiaco/actividad-1-infografia-Yareli-Perez#2]
![CICLO DE VIDA DE DESARROLLO DE SOFTWARE](https://user-images.githubusercontent.com/71900936/186543711-15605ffc-54a6-48b6-91d8-9a5d6a3f5f25.jpg)

**Comment by josealfredo79** [comment]
Falta calificacion

**Comment by mel-16** [comment]
15 Le falta Explicación

**Comment by josealfredo79** [comment]
Revisado...
